#!/sbin/sh

###
### Note
### 0. to freeze apps afterwards, try to get 'Root Uninstaller' (com.rootuninstaller or com.rootuninstaller.pro) by anttek.com .
### 1. do not remove 'Velvet' (has tts libs in usage) causes boot-loops (as noted in one of the blogs online).
### 2. do not remove 'Flipboard' (permanent widget in home pages). you can freeze it afterwards you remove it from the demo-home screens on your own.
### 3. 'StoryAlbum' might cause issues due to shared libs, but you can freeze it 
### 4. SamsungLink has two components dubbed 'samsung link platform services' the one that is  'SCONE_Android_ProxyService_Lib' ("com.sec.msc.nts.android.proxy") - I look into how safe it is to remove (I currently just freeze it on my device). the ones starting with samsunglink* are safe to remove though.
### 5. Peel is WatchOn app.
### 6. S_Translator is a really bad samsung translator that supports limited amount of languages, you can download Google Translate instead.
###

###BLOAT
rm -fr /system/app/aaIgnite*
rm -fr /system/app/ATTSmartWiFi*
rm -fr /system/app/BatteryTracer*
rm -fr /system/app/Books*
rm -fr /system/app/BoostZone*
rm -fr /system/app/Bug2Go*
rm -fr /system/app/CangjieQwertyPack*
rm -fr /system/app/ChatON*
rm -fr /system/app/Chrome*
rm -fr /system/app/ChromeWithBrowser*
rm -fr /system/app/ChsHandWritePack*
rm -fr /system/app/ChsPack*
rm -fr /system/app/ChtPack*
rm -fr /system/app/CityID*
rm -fr /system/app/CloudPrint*
rm -fr /system/app/com.mobitv.client.tv*
rm -fr /system/app/ConnectionsOptimizer*
rm -fr /system/app/Cricket-Connect*
rm -fr /system/app/CricketLauncher_MyAccount*
rm -fr /system/app/DigitalLocker*
rm -fr /system/app/Drive*
rm -fr /system/app/EditorsDocs*
rm -fr /system/app/Evernote*
rm -fr /system/app/facebook*
rm -fr /system/app/Facebook*
rm -fr /system/app/Famigo*
rm -fr /system/app/FBAppManager*
rm -fr /system/app/FBInstagram*
rm -fr /system/app/FeaturedApps*
rm -fr /system/app/FrenchPack*
rm -fr /system/app/GadgetGuardian*
rm -fr /system/app/GoogleDrive*
rm -fr /system/app/GoogleHindiIME*
rm -fr /system/app/GooglePinyinIME*
rm -fr /system/app/Hangouts*
rm -fr /system/app/IPLog*
rm -fr /system/app/IQDataUploadReport*
rm -fr /system/app/iWnnIME*
rm -fr /system/app/KoreanIME*
rm -fr /system/app/Magazines*
rm -fr /system/app/Maps*
rm -fr /system/app/Mi-EasyAccess*
rm -fr /system/app/MobileZone*
rm -fr /system/app/moffice*
rm -fr /system/app/MSSkype*
rm -fr /system/app/MuveLauncher-release*
rm -fr /system/app/Navigator*
rm -fr /system/app/Newsstand*
rm -fr /system/app/NotesPad*
rm -fr /system/app/NoteWidget*
rm -fr /system/app/Paypal*
rm -fr /system/app/PayWithPaypal*
rm -fr /system/app/Peel_*
rm -fr /system/app/Plants_Vs_Zombies*
rm -fr /system/app/PlayGames*
rm -fr /system/app/PlusOne*
rm -fr /system/app/PolarisViewer*
rm -fr /system/app/Quickoffice*
rm -fr /system/app/RealRacing*
rm -fr /system/app/S_Translat*
rm -fr /system/app/SamsungGame*
rm -fr /system/app/SamsungGames*
rm -fr /system/app/SamsungHub*
rm -fr /system/app/SamsungWallet*
rm -fr /system/app/Shop*
rm -fr /system/app/Shopmusic*
rm -fr /system/app/slackerradio*
rm -fr /system/app/SpanishPack*
rm -fr /system/app/SPR_Skyfire_*
rm -fr /system/app/SprintID*
rm -fr /system/app/SprintInstaller*
rm -fr /system/app/SprintZone*
rm -fr /system/app/StoryAlbum*
rm -fr /system/app/Swype*
rm -fr /system/app/talkback*
rm -fr /system/app/Timer*
rm -fr /system/app/TouchPal*
rm -fr /system/app/Translate*
rm -fr /system/app/TravelService*
rm -fr /system/app/TravelWidget*
rm -fr /system/app/TripAdvisor*
rm -fr /system/app/Twitter*
rm -fr /system/app/WhatsApp*
rm -fr /system/app/WiFiShare*
rm -fr /system/app/WorldTime*
rm -fr /system/app/xtra_t_app*
rm -fr /system/app/YahooNews*
rm -fr /system/app/YahooStocks*
rm -fr /system/app/YouTube*
rm -fr /system/app/YPmobile*
rm -fr /system/app/ZteNote*
rm -fr /system/etc/install-recovery.cfg
rm -fr /system/etc/recovery-resource.dat
rm -fr /system/lib/libgames_rtmp_jni.so
rm -fr /system/lib/libSwypeCore.so
rm -fr /system/lib/libvideochat_jni.so
rm -fr /system/media/video/AndroidInSpace*mp4
rm -fr /system/media/video/Sunset*mp4
rm -fr /system/partner-app/Cricket411*
rm -fr /system/partner-app/Cricket_MyBackup*
rm -fr /system/partner-app/CricketMoviusProdHTTPS*
rm -fr /system/partner-app/cricketnav*
rm -fr /system/partner-app/facebook*
rm -fr /system/partner-app/Facebook*
rm -fr /system/partner-app/GameloftHub*
rm -fr /system/partner-app/moffice*
rm -fr /system/partner-app/MyMizmo*
rm -fr /system/partner-app/Twitter*
rm -fr /system/partner-app/wifi*
rm -fr /system/priv-app/BodyGuardApp*
rm -fr /system/priv-app/DemoMode*
rm -fr /system/priv-app/DogfoodSurvey*
rm -fr /system/priv-app/DriveActivator*
rm -fr /system/priv-app/FBInstaller*
rm -fr /system/priv-app/fswriter*
rm -fr /system/priv-app/GoogleNews*
rm -fr /system/priv-app/GooglePay*
rm -fr /system/priv-app/GuideMe*
rm -fr /system/priv-app/LGBrowser*
rm -fr /system/priv-app/LGEmail*
rm -fr /system/priv-app/LGMemo*
rm -fr /system/priv-app/LGQMemo*
rm -fr /system/priv-app/LGTasks*
rm -fr /system/priv-app/Moodles*
rm -fr /system/priv-app/MotoAssist*
rm -fr /system/priv-app/MotoCare*
rm -fr /system/priv-app/Paypal*
rm -fr /system/priv-app/PayWithPaypal*
rm -fr /system/priv-app/PowerPoint*
rm -fr /system/priv-app/SamsungBilling*
rm -fr /system/priv-app/SamsungLink*
rm -fr /system/priv-app/SamsungPay*
rm -fr /system/priv-app/SamsungWallet*
rm -fr /system/priv-app/SecureFolder*
rm -fr /system/priv-app/Sprint_Installer*
rm -fr /system/priv-app/SprintID*
rm -fr /system/priv-app/SprintInstaller*
rm -fr /system/priv-app/SprintZone*
rm -fr /system/priv-app/StoryAlbum*
rm -fr /system/priv-app/Wallet*
rm -fr /system/priv-app/Word_Samsung*
rm -fr /system/priv-app/Zone-Sprint*
rm -fr /system/priv-app/ZteBrowser*
rm -fr /system/recovery-from-boot.p